[tool.black]
line-length = 79
target-version = ["py311"]

[tool.flake8]
max-line-length = 80
ignore = "E203, W503"
exclude = ".git, __pycache__, .venv"
select = "E,F,W,C"

[build-system]
requires = ["black", "flake8"]
build-backend = "setuptools.build_meta"